name: lint

on:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: '${{ github.workflow }}-${{ inputs.platform }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.sha }}'
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Install clang-format Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libncurses5
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Python
        uses: actions/setup-python@v4
      - name: Install Pip Packages
        run: pip install -r ${GITHUB_WORKSPACE}/requirements.txt
      - name: Download Resources
        run: python ${GITHUB_WORKSPACE}/download_resources.py
      - name: pre-commit
        uses: ./.github/actions/pre_commit
        with:
          base_ref: ${{ github.event.pull_request.base.sha && github.event.pull_request.base.sha || github.event.base_ref }}
