name: linux_COBALT_9

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - 'COBALT_9'
  push:
    branches:
      - 'COBALT_9'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  linux:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: linux
      nightly: ${{ github.event.inputs.nightly }}
