name: raspi-2_rc_11

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches:
      - 'rc_11'
  push:
    branches:
      - 'rc_11'
  workflow_dispatch:
    inputs:
      nightly:
        description: 'Nightly workflow.'
        required: true
        type: boolean
        default: false

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  raspi-2:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
    with:
      platform: raspi-2
      nightly: ${{ github.event.inputs.nightly }}
